### ISSUE TITLE
Line annotations not working with properties

### ISSUE THREAD

**Issue by Tachi107** [oxlip-lang/oal#20]
Hi! I've encountered a somewhat strange behaviour in oal, which to me looks like a bug. When annotating property declarations, I'm only able to use inline annotations, and not line (above) annotations.

It's clearer with some examples.

The following Oxlip code:

```oxlip
let id = 'id int `title: my title, description: my description`;

res /test on get -> { id };
```

produces (some fields omitted for brevity):

```yaml
schema:
  type: object
  properties:
    id:
      title: my title
      description: my description
      type: integer
```

On the other hand, this other Oxlip code:

```oxlip
# title: my title
# description: my description
let id = 'id int;

res /test on get -> { id };
```

produces:

```yaml
schema:
  type: object
  properties:
    id:
      type: integer
```

Note that there are no title or description keys.

I'm guessing that this is because in the first example the annotations get assigned to the "implicit" int type, while in the second case they get assigned to the property and discarded, for some reason.

I'm inclined to think this is what's happening also because given this Oxlip code:

```oxlip
# title: my title
let idType = int;

# description: this is going to get discarded
let id = 'id idType;

res /test on get -> { id };
```

I get:

```yaml
schema:
  type: object
  properties:
    id:
      title: my title
      type: integer
```

As you can see, the description is discarded.

Note that this also seems to contradict the example at <https://www.oxlip-lang.org/doc/overview.html#properties>, where a description is added to a property declaration like above.

For completeness, the following Oxlip code works as intended:

```oxlip
# title: my title
let idType = int;

let id = 'id idType `description: my description`;

res /test on get -> { id };
```

as it produces:

```yaml
schema:
  type: object
  properties:
    id:
      title: my title
      description: my description
      type: integer
```
